### ISSUE TITLE
Domain validation fails on TokTok, YouTube

### ISSUE THREAD

**Issue by katzgrau** [rtCamp/trust-txt#11]
The current domain validation regex at this line:

https://github.com/rtCamp/trust-txt/blob/84ac50fc4ffd9970cce4c866647348e5bb94e32a/inc/save.php#L94

Does not match the `@` symbol standard in TikTok and YouTube account URLs.

This results in a validation error that prevents saving:

<img width="836" alt="image" src="https://github.com/rtCamp/trust-txt/assets/134221/13537441-c130-4224-a54a-43cf21e542e5">

May file a PR if I have time, but it's an easy fix.

**Comment by shubham07kb** [comment]
Issue resolved :+1:
