### ISSUE TITLE
trust.txt update

### ISSUE THREAD

**Issue by Niel-S** [rtCamp/trust-txt#12]
Right now the tool validates that the variables in the file are among those that are in the spec. Well, we just added a new variable. 

datatrainingallowed=

So that's the request, just add that to the list that you already have in the plugin.

If you like, you can read about it in the new spec, which is attached. 
[trust-txt-spec-1-4.pdf](https://github.com/rtCamp/trust-txt/files/15248560/trust-txt-spec-1-4.pdf)

**Comment by Niel-S** [comment]
As per Spec document

 `datatrainingallowed` has validation YES or NO , only 2 options should be available
All previous variable Fields can be used more than once with the exception of `datatrainingallowed`, which should be used only once

**Comment by shubham07kb** [comment]
Also add support for customer and vendor.
