### ISSUE TITLE
Trust-txt is not supporting the .well-known Directory

### ISSUE THREAD

**Issue by nitun** [rtCamp/trust-txt#3]
https://rtcamp.slack.com/archives/C7VFLQZLJ/p1645472516467419?thread_ts=1645436028.150259&cid=C7VFLQZLJ 
@mangesh I don't know the exact issue description for this task. 
Please feel free to update it.

**Comment by mangesh** [comment]
> https://rtcamp.slack.com/archives/C7VFLQZLJ/p1645472516467419?thread_ts=1645436028.150259&cid=C7VFLQZLJ @mangesh I don't know the exact issue description for this task. Please feel free to update it.

Most of the servers by default allow access to the `.well-known` directory and our plugin is not configured to serve most of the servers.

**Comment by nitun** [comment]
@mangesh since you updated the plugin on WP repository https://wordpress.org/plugins/trust-txt/, you should have updated the readme as well for compatibility with latest WP version. 

![Trust_txt_Manager_–_WordPress_plugin___WordPress_org](https://user-images.githubusercontent.com/1140051/155353896-62470941-d43f-4b8e-83c6-b8961b14f5bb.png)

**Comment by mangesh** [comment]
I can bump this on SVN without pushing the update. Should I go ahead?

**Comment by nitun** [comment]
Yes sir. That is why I commented on this task.

**Comment by nitun** [comment]
I have provided committer access to your username. Please check if that works.
![Trust_txt_Manager__advanced_view__–_WordPress_plugin___WordPress_org](https://user-images.githubusercontent.com/1140051/155459976-26b0b463-c605-49ad-accc-0408753bd175.png)

**Comment by mangesh** [comment]
This is fixed. We can close this issue.

**Comment by vishalkakadiya** [comment]
@nitun looks like this issue is resolved, can we close this issue now?

CC @mangesh

**Comment by nitun** [comment]
Yeah. I believe so. @mangesh please confirm and close this issue.

**Comment by mangesh** [comment]
@vishalkakadiya Yes, we can close this issue.

**Comment by mangesh** [comment]
@vishalkakadiya Yes, we can close this issue.

**Comment by vishalkakadiya** [comment]
@nitun @mangesh Thank you for the confirmation, closing this issue now.
