### ISSUE TITLE
PHP notice displayed after saving the trust.txt settings

### ISSUE THREAD

**Issue by pavanpatil1** [rtCamp/trust-txt#6]
PHP notice related to Undefined index is displayed on debug log after saving the trust.txt manager settings. Below notice is shown. 

`PHP Notice:  Undefined index: trust_path in app\public\wp-content\plugins\trust-txt\inc\save.php on line 55`

Steps to reproduce: 
1. log in to the WP dashboard and Navigate to Settings -> trust.txt
2. Enter the URL and click on save settings. 

https://user-images.githubusercontent.com/44057535/167795298-82ff563e-40ec-4201-bfd8-364f09b10012.mp4

**Comment by shubham07kb** [comment]
Issue resolved :+1:
